apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: taskwatch
    user: taskwatch_user
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: 'taskwatch_password'
    editable: true
    version: 1
